### ISSUE TITLE
Graph layout options other then Force

### ISSUE THREAD

**Issue by buildvoc10** [daxcore/mkdocs-obsidian-interactive-graph-plugin#2]
Thank you for sharing this plugin for MKDoc,s have it deployed at http://preview.pic2bim.co.uk/ for testing. Was wondering if you had tested any other graph layouts other than force?

**Comment by daxcore** [comment]
Welcome. Which graph layout do u miss? The forced one was the only layout that matched my idea of the graph.

**Comment by buildvoc10** [comment]
Maybe breadthfirst which hierarchical graph layout?

**Comment by daxcore** [comment]
not sure which layout u mean. maybe u can send a link to an echarts demo. in general the python plugin generates a json file with a special format matching the forced layout, like this:

```
{
  "nodes": [
    {
      "id": "0",
      "name": "Welcome",
      ...
    },
    {
      "id": "1",
      "name": "Concept",
      ...
    },
    ...
  ],
  "links": [
    {
      "source": "0",
      "target": "1"
    },
    ...
```

i guess this format is special for the forced layout.

**Comment by buildvoc10** [comment]
dagre https://github.com/ecomfe/echarts-dagre is a good graph layout for showing information flow

**Comment by daxcore** [comment]
sorry this layout doesn't work for me. if it does for u, feel free to use it in your instance. generally it looks compatible to the force layout.

**Comment by buildvoc10** [comment]
Have you done any other test with mkdocs and network graphs

**Comment by daxcore** [comment]
unfortunately not, sorry.
